// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatingApp.DAL.Entity;

public partial class Photo
{
    public long Id { get; set; }

    public string Url { get; set; }

    public bool IsMain { get; set; }

    public string PublicId { get; set; }

    public long UserId { get; set; }

    public virtual User User { get; set; }
}