// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatingApp.DAL.Entity;

public partial class User
{
    public long Id { get; set; }

    public string UserName { get; set; }

    public string Password1 { get; set; }

    public DateTime? DateOfBirth { get; set; }

    public string KnownAs { get; set; }

    public DateTime? Creted { get; set; }

    public DateTime? LastActive { get; set; }

    public string Gender { get; set; }

    public string Indroduction { get; set; }

    public string LookingFor { get; set; }

    public string Interesets { get; set; }

    public string City { get; set; }

    public string Country { get; set; }

    public virtual ICollection<Photo> Photos { get; set; } = new List<Photo>();
}